# Standalone workflow to update changelog if necessary
name: Build changelog

on:
  workflow_dispatch:
  schedule:
           # ┌───────────── minute (0 - 59)
           # │ ┌───────────── hour (0 - 23)
           # │ │ ┌───────────── day of the month (1 - 31)
           # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
           # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
           # │ │ │ │ │
           # │ │ │ │ │
           # │ │ │ │ │
           # * * * * *
    - cron: '0 8 * * *'

jobs:
  changelog:
    uses: ./.github/workflows/reusable_publish_changelog.yml
