name: Docs

on:
  push:
    branches:
      - develop
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "examples/**"
      - "CHANGELOG.md"

jobs:
  release-docs:
    permissions:
      contents: write
      pages: write
    uses: ./.github/workflows/reusable_publish_docs.yml
    with:
      version: develop
      alias: stage
